### ISSUE TITLE
french and maybe some other translations broken, the return !

### ISSUE THREAD

**Issue by zelurker** [Pocket-Plane-Group/UnfinishedBusiness#7] opened 2020-04-23 18:11 UTC
Ok, I took 10 minutes to recreate this, to give you some very easy steps to reproduce, made a backup of my bg2ee folder for that, and uninstalled everything except the french translation, then using your version of ub :
choosing language 1 (french) and then installing the 1st element, boo abduction -> game freezes at launch
then uninstalling this and installing ub 26 from the pocketplane site, then choosing exactly the same options, language french, and then 1st element, boo abduction : everything works perfectly.

Now if you just don't want to fix things, it's fine, just write it down in the readme and you won't receive any issues ! :)
Since I am currently trying eet, I guess there are some eet fixes in your version, so I use it in english, english installation works fine. And also this kind of freeze happens when some non utf8 accents have been put in the dialog files (I know that after having worked on some translations, 1 of the worst bugs of bgee/bg2ee).

**Comment by AngelGryph** [comment] 2020-06-02 21:30
Look, it's not that I don't want to help you but I cannot fix what I can't reproduce.  And I am totally unable to recreate this one.  I've tried, but what you describe simply does not happen to me, or to the person who actually made the French translation.

**Comment by AngelGryph** [comment] 2020-06-02 21:34
Oh, and there now is a fully working Russian translation too.

**Comment by AngelGryph** [comment] 2020-06-03 17:55
The v28 release changes the way .tra files are handled (as part of implementing mod immutability), perhaps this also solves your issue.  I've installed the French translation on a clean BG2EE game like you suggested and was able to start a game normally.  (But then again, I could do this with v27 too.)

**Comment by AngelGryph** [comment] 2020-08-31 20:51
Closing this one again.  Completely unable to reproduce with the given steps, nobody else has reported this issue, no follow-up from the reporter after three months, and UB doesn't even alter the area where the issue happens to begin with.  Sorry, but there is nothing here that I can work with.

**Closed by AngelGryph** 2020-08-31 20:51 UTC
