### ISSUE TITLE
finally found the issue with the french translation !

### ISSUE THREAD

**Issue by zelurker** [Pocket-Plane-Group/UnfinishedBusiness#9] opened 2020-11-17 16:25 UTC
opened an issue about it quite a long while ago but it was impossible to reproduce it...
It's actually linked to uninstallation !

So... install something in french
then uninstall it
and reinstall it
launch baldursgateii -> frozen

It's not the only mod which has this problem, it's linked to the utf8 encoding, instead of failing silently it freezes in this case.
Solution : after having uninstalled, remove completely the ub directory and extract if from the archive to install from scratch, this way it works !

**Comment by AngelGryph** [comment] 2021-01-03 18:15
Because I am still completely unable to reproduce this I asked Jazira, who provided a few updates to the French translation for v28, to look into this.  He had never heard of it and was likewise not able to reproduce it, and only found one small issue with the French translation files (wwinterj.tra was in Unix format).

Please specify exactly which version you experience the problem with, as it may have been solved already in the current build.

**Comment by zelurker** [comment] 2021-01-04 00:44
What a curse... ! Well it was with v27 and weidu 247 in linux.
But anyway since there is some reliable way to work around this, it's ok
even without any fix.

Le dim. 3 janv. 2021 à 19:15, AngelGryph <notifications@github.com> a
écrit :

**Comment by AngelGryph** [comment] 2021-01-04 00:56
Mm, v27 is two years old and shipped with WeiDU 246, it wasn't updated for WeiDU 247 which was released only a few months ago.  That's actually one of the new features in v28; WeiDU 247 introduced a few changes that are incompatible with some older mods, and UB is one of them.  I'm not sure if that is what caused your issues, but I can't rule it out either.  Anyway, v28 is up now, perhaps it will solve your issue.

**Comment by zelurker** [comment] 2021-01-04 01:17
Ok good to know, I'll try that when I have time, but it won't be soon...
sorry for the trouble anyway, I would never have guessed that this thing
would be so elusive !

Le lun. 4 janv. 2021 à 01:56, AngelGryph <notifications@github.com> a
écrit :

**Comment by Jazira33** [comment] 2021-01-06 02:10
Hello Zelurker,
Since AngelGryph contacted you I've decided to do a big proofreading, modernization of the French translations files included in the latest release.
Hundreds of various typos have been corrected, encoding have been fixed, etc.

I am optimist that the problem you reported here is also fixed.

It would be great if you could try to reproduce the steps you described with the updated version and tell us what happens, thanks !

**Comment by AngelGryph** [comment] 2022-07-20 21:01
Closing this as there has been no update for more than a year.

**Closed by AngelGryph** 2022-07-20 21:01 UTC
